server:
  port: 8082

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/VaccinationCenterDB
    username: root
    password: Yy3$d7!W20235@
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect

  application:
    name: VACCINATION-CENTER-SERVICE






