# server port: 8081 to connect my first web-service - user service
server:
  port: 8081

# server port: 8082 to connect to the second web-service - vaccination service.

# datasource to connect my user service to mysql database. Here I am going to use design pattern - "one database per microservice". I am not going to use the shared database where all microservice accessing the same database.
# "one-database-per-microservice" design pattern  - here each microservice is going to have its own database.
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/CitizenDB
    username: root
    password: Yy3$d7!W20235@
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database.platform: org.hibernate.dialect.MySQL8Dialect

# Eureka server is going to have the name for all its microservices. So we have to put the application name below.
  application:
    name: CITIZEN-SERVICE

# Now create the connection and then database name 'CitizenDB' before that first install the database navigator plugin.
# 1. Installing Database Navigator plugin
# Open Setting dialogs and search for plugin: Select MarketPlace tab and type database: In the right panel (which shows Database Navigator) click on install and then click on restart IDE.
# 2. Now if you have installed MySQL server and MySQL Workbench in your machine then open workbench and create one schema
# where you will be giving connection_name, database_name, host_name, port_number etc.







